; Malware Research Suite
; PE/COFF constants reference
; Static-analysis reference only.

IMAGE_DOS_SIGNATURE        EQU 05A4Dh
IMAGE_NT_SIGNATURE         EQU 00004550h

IMAGE_FILE_MACHINE_I386    EQU 014Ch
IMAGE_FILE_MACHINE_AMD64   EQU 08664h
IMAGE_FILE_MACHINE_ARM64   EQU 0AA64h

PE32_MAGIC                 EQU 010Bh
PE32_PLUS_MAGIC            EQU 020Bh

IMAGE_SCN_CNT_CODE         EQU 00000020h
IMAGE_SCN_CNT_INITIALIZED   EQU 00000040h
IMAGE_SCN_CNT_UNINITIALIZED EQU 00000080h

IMAGE_SCN_MEM_EXECUTE      EQU 20000000h
IMAGE_SCN_MEM_READ         EQU 40000000h
IMAGE_SCN_MEM_WRITE        EQU 80000000h

IMAGE_DIRECTORY_ENTRY_EXPORT    EQU 0
IMAGE_DIRECTORY_ENTRY_IMPORT    EQU 1
IMAGE_DIRECTORY_ENTRY_RESOURCE  EQU 2
IMAGE_DIRECTORY_ENTRY_EXCEPTION EQU 3
IMAGE_DIRECTORY_ENTRY_SECURITY  EQU 4
IMAGE_DIRECTORY_ENTRY_BASERELOC EQU 5
IMAGE_DIRECTORY_ENTRY_DEBUG     EQU 6
IMAGE_DIRECTORY_ENTRY_TLS       EQU 9
IMAGE_DIRECTORY_ENTRY_DELAY_IMPORT EQU 13

IMAGE_SUBSYSTEM_UNKNOWN              EQU 0
IMAGE_SUBSYSTEM_NATIVE               EQU 1
IMAGE_SUBSYSTEM_WINDOWS_GUI          EQU 2
IMAGE_SUBSYSTEM_WINDOWS_CUI          EQU 3

; DOS header offsets

DOS_E_MAGIC             EQU 00h
DOS_E_LFANEW            EQU 3Ch

; NT headers offsets

NT_SIGNATURE            EQU 00h
NT_FILE_HEADER          EQU 04h
NT_OPTIONAL_HEADER      EQU 18h

; IMAGE_FILE_HEADER offsets

FILE_MACHINE             EQU 00h
FILE_NUMBER_OF_SECTIONS  EQU 02h
FILE_TIMESTAMP            EQU 04h
FILE_SIZE_OF_OPTIONAL    EQU 10h
FILE_CHARACTERISTICS     EQU 12h

; IMAGE_OPTIONAL_HEADER32 offsets

OPT_MAGIC                EQU 00h
OPT_ENTRY_POINT          EQU 10h
OPT_IMAGE_BASE           EQU 1Ch
OPT_SIZE_OF_IMAGE        EQU 38h
OPT_SUBSYSTEM            EQU 44h
OPT_DLL_CHARACTERISTICS  EQU 46h
OPT_NUMBER_OF_RVA_SIZES  EQU 5Ch

; Section header offsets

SECTION_NAME             EQU 00h
SECTION_VIRTUAL_SIZE     EQU 08h
SECTION_VIRTUAL_ADDRESS  EQU 0Ch
SECTION_RAW_SIZE         EQU 10h
SECTION_RAW_OFFSET       EQU 14h
SECTION_CHARACTERISTICS  EQU 24h
